/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoattendance;

import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.net.URI;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author imn99
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginHome
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        icoPass = new javax.swing.JLabel();
        icouser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AIUB = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();
        Linkedin = new javax.swing.JLabel();
        facebook = new javax.swing.JLabel();
        Searchfield = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        youtube = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        clicktogo = new javax.swing.JLabel();
        Log = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(51, 0, 102))); // NOI18N
        username.setSelectionColor(new java.awt.Color(51, 0, 102));
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 340, 310, 60));

        password.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(51, 0, 102))); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 440, 260, 60));

        icoPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/Password_40px.png"))); // NOI18N
        jPanel1.add(icoPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 450, -1, -1));

        icouser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/User_40px.png"))); // NOI18N
        jPanel1.add(icouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setText("Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 230, -1, 50));

        AIUB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/50 AIUB.png"))); // NOI18N
        AIUB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AIUBMouseClicked(evt);
            }
        });
        jPanel1.add(AIUB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 770, -1, -1));

        twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/Twitter_50px.png"))); // NOI18N
        twitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twitterMouseClicked(evt);
            }
        });
        jPanel1.add(twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 770, -1, -1));

        Linkedin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/LinkedIn_50px.png"))); // NOI18N
        Linkedin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LinkedinMouseClicked(evt);
            }
        });
        jPanel1.add(Linkedin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 770, -1, -1));

        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/Facebook_50px.png"))); // NOI18N
        facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookMouseClicked(evt);
            }
        });
        jPanel1.add(facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 770, -1, -1));

        Searchfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchfieldKeyPressed(evt);
            }
        });
        jPanel1.add(Searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 80, 140, 30));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/Invisible_40px.png"))); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 450, 50, 40));

        youtube.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/YouTube_50px.png"))); // NOI18N
        youtube.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                youtubeMouseClicked(evt);
            }
        });
        jPanel1.add(youtube, new org.netbeans.lib.awtextra.AbsoluteConstraints(1630, 770, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/Google_27px.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 80, 110, 30));

        clicktogo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clicktogo.setForeground(new java.awt.Color(51, 0, 102));
        clicktogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/click.png"))); // NOI18N
        clicktogo.setText("    Click to go..!");
        clicktogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(clicktogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 890, 180, -1));

        Log.setBackground(new java.awt.Color(204, 204, 204));
        Log.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        Log.setForeground(new java.awt.Color(51, 0, 102));
        Log.setText("Sign in");
        Log.setBorder(null);
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });
        jPanel1.add(Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 570, 200, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/interface (.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1900, 0, 50, 1140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
        // TODO add your handling code here:
        login();

    }//GEN-LAST:event_LogActionPerformed

    public void login()
    {
        String user = username.getText();
        String pass = password.getText();

        try
        {
            if(user.equals("AIUB") && (pass.equals("aiub")))
            {
                // username.setText(null);
                // password.setText(null);

                Panel1 p = new Panel1();
                p.setVisible(true);
                p.pack();
                p.setLocationRelativeTo(null);
                p.setDefaultCloseOperation(Panel1.EXIT_ON_CLOSE);
                dispose();

            }
            else
            {
                JOptionPane.showMessageDialog(null,"Enter User Name & Password Correctly","Error",0);
            }

        }
        catch (Exception e)
        {
            System.out.println(e);
        }
    }
    
    private void AIUBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AIUBMouseClicked
        // TODO add your handling code here:
         Desktop browser = Desktop.getDesktop();
        
        try
        {
            browser.browse(new URI("http:/www.aiub.edu"));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_AIUBMouseClicked

    private void facebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookMouseClicked
        // TODO add your handling code here:
         Desktop browser = Desktop.getDesktop();
        
        try
        {
            browser.browse(new URI("http:/www.Facebook.com"));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_facebookMouseClicked

    private void twitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitterMouseClicked
        // TODO add your handling code here:
         Desktop browser = Desktop.getDesktop();
        
        try
        {
            browser.browse(new URI("http:/www.twitter.com"));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_twitterMouseClicked

    private void LinkedinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LinkedinMouseClicked
        // TODO add your handling code here:
         Desktop browser = Desktop.getDesktop();
        
        try
        {
            browser.browse(new URI("http:/www.Linkedin.com"));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_LinkedinMouseClicked

    private void youtubeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_youtubeMouseClicked
        // TODO add your handling code here:
         Desktop browser = Desktop.getDesktop();
        
        try
        {
            browser.browse(new URI("http:/www.youtube.com"));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_youtubeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void search()
    {
         String a = Searchfield.getText().replace(" ", "");
        try
        {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create("http:/www.google.com/search?hl=en&q="+a+"&btnG=Google+search"));
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if(jToggleButton2.isSelected())
        {
            jToggleButton2.setIcon(new ImageIcon(getClass().getResource("/ToggleIcons/Eye_40px.png")));
            password.setEchoChar((char)0);
        }
        else
        {
            jToggleButton2.setIcon(new ImageIcon(getClass().getResource("/ToggleIcons/Invisible_40px.png")));
            password.setEchoChar('•');
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void SearchfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchfieldKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            search();
        }
    }//GEN-LAST:event_SearchfieldKeyPressed

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            login();
        }
    }//GEN-LAST:event_usernameKeyPressed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            login();
        }
    }//GEN-LAST:event_passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AIUB;
    private javax.swing.JLabel Linkedin;
    private javax.swing.JButton Log;
    private javax.swing.JTextField Searchfield;
    private javax.swing.JLabel clicktogo;
    private javax.swing.JLabel facebook;
    private javax.swing.JLabel icoPass;
    private javax.swing.JLabel icouser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel twitter;
    private javax.swing.JTextField username;
    private javax.swing.JLabel youtube;
    // End of variables declaration//GEN-END:variables
}
