package autoattendance;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imn99
 */
public class TakeAttandance extends javax.swing.JFrame {

    /**
     * Creates new form TakeAttandance
     */
    public TakeAttandance() {
        initComponents();
        loadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        attendanceIDTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        attendanceCourseComboBox1 = new javax.swing.JComboBox();
        attendanceSectionComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        Back = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Section:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Course:");

        attendanceIDTextField.setBackground(studentPanel1.getBackground());
        attendanceIDTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        attendanceIDTextField.setForeground(new java.awt.Color(255, 255, 255));
        attendanceIDTextField.setBorder(null);
        attendanceIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceIDTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Take Attendance");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, null, null));

        attendanceCourseComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        attendanceCourseComboBox1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        attendanceCourseComboBox1.setBorder(attendanceCourseComboBox1.getBorder());
        attendanceCourseComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceCourseComboBox1ActionPerformed(evt);
            }
        });

        attendanceSectionComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        attendanceSectionComboBox1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton1.setBackground(studentPanel1.getBackground());
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Take Attendance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/Go Back_35px.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/Delete_35px.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ToggleIcons/Calendar_30px.png"))); // NOI18N
        jButton2.setText("Take Attandance With Date");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentPanel1Layout = new javax.swing.GroupLayout(studentPanel1);
        studentPanel1.setLayout(studentPanel1Layout);
        studentPanel1Layout.setHorizontalGroup(
            studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanel1Layout.createSequentialGroup()
                .addGap(773, 773, 773)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(attendanceCourseComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attendanceSectionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(studentPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jSeparator2))
                                .addComponent(attendanceIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(825, 825, 825))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(805, 805, 805))))
            .addGroup(studentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        studentPanel1Layout.setVerticalGroup(
            studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(studentPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215)
                        .addComponent(attendanceIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(attendanceCourseComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(studentPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(studentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attendanceSectionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(studentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attendanceIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceIDTextFieldActionPerformed
        // TODO add your handling code here:
        attendanceIDTextField = (JTextField) evt.getSource();
        String text = attendanceIDTextField.getText();
        attendanceIDTextField.setText(text.toUpperCase());
        if (text.length() == 10) {
            attendance();
        }
    }//GEN-LAST:event_attendanceIDTextFieldActionPerformed

    private void attendanceCourseComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceCourseComboBox1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            attendanceSectionComboBox1.removeAllItems();
            String courseName = "";
            DatabaseConnection dbConnection = new DatabaseConnection();
            Connection con = dbConnection.createConnection();

            String sql = "Select * From course";
            Statement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);
            String courseName2 = attendanceCourseComboBox1.getSelectedItem().toString();
            ResultSet rs1 = st.executeQuery("SELECT section FROM `course` where `course`.`Course_Name` = \'" + courseName2 + "\'");

            while (rs1.next()) {

                String section = rs1.getString("Section");
                attendanceSectionComboBox1.addItem(section);
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attendanceCourseComboBox1ActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        new Panel1().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        attendance();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TakeAttandanceWithDate A = new TakeAttandanceWithDate();
        A.setVisible(true);
        A.pack();
        A.setLocationRelativeTo(null);
        A.setDefaultCloseOperation(TakeAttandance.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    void attendance() {
        DatabaseConnection dbConnection = new DatabaseConnection();
        //int recordNumber = 0; 
        String studentId = attendanceIDTextField.getText();
        String courseName = attendanceCourseComboBox1.getSelectedItem().toString();
        String section = attendanceSectionComboBox1.getSelectedItem().toString();
        try {

            Connection con = dbConnection.createConnection();
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("SELECT * FROM `students` where `students`.`Student_Id` = \'" + studentId + "\'");
            rs.next();

            ResultSet rs1 = st.executeQuery("SELECT * FROM `course` where `course`.`Course_Name` = \'" + courseName + "\' and `course`.`Section` = \'" + section + "\' ");
            int cid = 0;
            if (rs1.next()) {
                cid = rs1.getInt("id");
            }
            Statement st1 = con.createStatement();
            ResultSet rs3 = st1.executeQuery("SELECT COUNT(*) FROM `studentcourse` WHERE `studentcourse`.`CID` = \'" + cid + "\' AND `studentcourse`.`SID`= \'" + studentId + "\'");

            if (rs3.next()) {

                try {
                    Statement st3 = con.createStatement();
                    ResultSet rs4 = st3.executeQuery("SELECT * FROM `report` where `report`.`student_id` = \'" + studentId + "\' and `report`.`course_id` =" + cid + " and `report`.`date`= CURDATE()");

                    if (!rs4.next()) {
                        Statement st2 = con.createStatement();
                        st2.executeUpdate("INSERT INTO `report`( `student_id`, `course_id`, `date`) VALUES ('" + studentId + "'," + cid + ",CURDATE());");
                        //st2.executeUpdate("INSERT INTO `report` (`student_id`, `course_id`)  VALUES ('"+studentId+"','"+cid+"','CURDATE()');");
                        JOptionPane.showMessageDialog(null, "Attendance Taken");

                    } else {

                        JOptionPane.showMessageDialog(null, "Attendance already taken");
                    }
                } catch (Exception e) {

                    JOptionPane.showMessageDialog(null, "Student is not enlisted on the course");
                    System.out.println(e);
                }
            } else {

            }

        } catch (Exception e) {

            System.out.println(e);
            e.printStackTrace();

        }
        attendanceIDTextField.setText("");
    }

    void loadComboBox() {
        try {

            String courseName = "";
            DatabaseConnection dbConnection = new DatabaseConnection();
            Connection con = dbConnection.createConnection();

            HashSet<String> course = new HashSet<String>();

            String sql = "Select * From course";
            Statement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {

                courseName = rs.getString("Course_Name");
                course.add(courseName);

            }

            for (String s : course) {
                attendanceCourseComboBox1.addItem(s);

            }
            String courseName2 = attendanceCourseComboBox1.getSelectedItem().toString();
            ResultSet rs1 = st.executeQuery("SELECT section FROM `course` where `course`.`Course_Name` = \'" + courseName2 + "\'");

            while (rs1.next()) {

                String section = rs1.getString("Section");
                attendanceSectionComboBox1.addItem(section);
            }

        } catch (Exception ex) {

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeAttandance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeAttandance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeAttandance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeAttandance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeAttandance().setVisible(true);
            }
        });
    }
    public String id = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Exit;
    private javax.swing.JComboBox attendanceCourseComboBox1;
    private javax.swing.JTextField attendanceIDTextField;
    private javax.swing.JComboBox attendanceSectionComboBox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel studentPanel1;
    // End of variables declaration//GEN-END:variables
}
